prompt === Create table GD_Employee ===

create table GD_Employee
  (id integer generated by default on null as identity not null,
   employee_id Integer                                        not null,
   gadget_id   Integer                                        not null);

comment on table GD_Employee             is 'GAMITY. Рабочие (01.11.2020)';

comment on column GD_Employee.id          is 'Id';
comment on column GD_Employee.employee_id is 'Id сотрудника';
comment on column GD_Employee.gadget_id   is 'Id гаджета';

alter table GD_Employee add
  constraint PK_GD_Emp
    primary key (id) using index tablespace Indexes;
alter table GD_Employee add
  constraint FK_GD_Emp_2_Gdt
    foreign key (gadget_id)
    references GD_Gadget (id);
alter table GD_Employee add
  constraint FK_GD_Emp_2_Emp_Per
    foreign key (employee_id)
    references GD_Emp_Personnel (id);
