prompt === Create table GD_Emp_Employer ===

create table GD_Emp_Employer
  (id integer generated by default on null as identity not null,
   name VarChar2(2000)                                                ,
   inn  VarChar2(  30)                                                );

comment on table GD_Emp_Employer      is 'GAMITY. Отдел кадров. Работодатели (01.11.2020)';

comment on column GD_Emp_Employer.inn  is 'ИНН';
comment on column GD_Emp_Employer.id   is 'Id';
comment on column GD_Emp_Employer.name is 'Наименование';

alter table GD_Emp_Employer add
  constraint PK_GD_Emp_Emp
    primary key (id) using index tablespace Indexes;
alter table GD_Emp_Employer add
  constraint UK_GD_Emp_Emp_4_inn
    unique (inn) using index tablespace Indexes;
