prompt === Create table GD_Gadget ===

create table GD_Gadget
  (id integer generated by default on null as identity not null,
   mac_address  VarChar2(100)                                        not null,
   phone_number Integer                                              not null);

comment on table GD_Gadget              is 'GAMITY. Гаджеты (01.11.2020)';

comment on column GD_Gadget.id           is 'Id';
comment on column GD_Gadget.mac_address  is 'MAC адрес';
comment on column GD_Gadget.phone_number is '№ телефона';

alter table GD_Gadget add
  constraint PK_GD_Gdt
    primary key (id) using index tablespace Indexes;
alter table GD_Gadget add
  constraint UK_GD_Gdt_4_mac_adr
    unique (mac_address) using index tablespace Indexes;
