prompt === Create table GD_Object ===

create table GD_Object
  (id integer generated by default on null as identity not null,
   object_name              VarChar2(2000)                                        not null,
   government_contract_num  VarChar2(  30)                                                ,
   government_contract_date Date                                                          ,
   building_area            Number                                                        ,
   owner                    VarChar2(2000)                                                ,
   general_contractor       VarChar2(2000)                                                ,
   building_license_num     VarChar2(  30)                                                ,
   building_license_date    Date                                                          );

comment on table GD_Object                          is 'GAMITY. Строительные объекты (01.11.2020)';

comment on column GD_Object.id                       is 'Id';
comment on column GD_Object.object_name              is 'Наименование объекта';
comment on column GD_Object.government_contract_num  is 'Государственный контракт №';
comment on column GD_Object.government_contract_date is 'Государственный контракт от';
comment on column GD_Object.building_area            is 'Строительная площадь (м2)';
comment on column GD_Object.owner                    is 'Заказчик';
comment on column GD_Object.general_contractor       is 'Генеральный подрядчик';
comment on column GD_Object.building_license_num     is 'Разрешение на строительство №';
comment on column GD_Object.building_license_date    is 'Разрешение на строительство от';

alter table GD_Object add
  constraint PK_GD_Obj
    primary key (id) using index tablespace Indexes;
