prompt === Create table GD_Trace ===

create table GD_Trace
  (id integer generated by default on null as identity not null,
   object_id     Integer                                                   ,
   employee_id   Integer                                           not null,
   work_shift_id Integer                                                   ,
   latitude      Number                                            not null,
   longitude     Number                                            not null,
   altitude      Number                                            not null,
   gadget_id     Integer                                           not null,
   in_work       Integer                                                   ,
   in_area       Char   (1)                                                ,
   date_time     Date                                              not null);

comment on table GD_Trace               is 'GAMITY. Трассировка телеметрии (01.11.2020)';

comment on column GD_Trace.id            is 'Id';
comment on column GD_Trace.object_id     is 'Id объекта';
comment on column GD_Trace.employee_id   is 'Id работника';
comment on column GD_Trace.work_shift_id is 'Id смены';
comment on column GD_Trace.latitude      is 'Широта';
comment on column GD_Trace.longitude     is 'Долгота';
comment on column GD_Trace.altitude      is 'Высота';
comment on column GD_Trace.gadget_id     is 'Id гаджета';
comment on column GD_Trace.in_work       is '1 - не обработано';
comment on column GD_Trace.in_area       is 'В пределах объекта (Y/N)';
comment on column GD_Trace.date_time     is 'Дата/время';

alter table GD_Trace add
  constraint PK_GD_Trc
    primary key (id) using index tablespace Indexes;
alter table GD_Trace add
  constraint FK_GD_Trc_2_Gdt
    foreign key (gadget_id)
    references GD_Gadget (id);
alter table GD_Trace add
  constraint FK_GD_Trc_2_Emp
    foreign key (employee_id)
    references GD_Employee (id);
alter table GD_Trace add
  constraint FK_GD_Trc_2_Obj
    foreign key (object_id)
    references GD_Object (id);
