prompt === Create table GD_Work_Shift ===

create table GD_Work_Shift
  (id integer generated by default on null as identity not null,
   object_id       Integer                                        not null,
   date_time_begin Date                                           not null,
   date_time_end   Date                                                   ,
   all_time        Number                                                 ,
   productive_time Number                                                 ,
   employee_id     Integer                                        not null,
   is_open         Integer                                                ,
   count_sos       Integer                                                ,
   gadget_id       Integer                                        not null);

comment on table GD_Work_Shift                 is 'GAMITY. Смены (01.11.2020)';

comment on column GD_Work_Shift.id              is 'Id';
comment on column GD_Work_Shift.object_id       is 'Id объекта';
comment on column GD_Work_Shift.date_time_begin is 'Дата/время начала смены';
comment on column GD_Work_Shift.date_time_end   is 'Дата/время окончания смены';
comment on column GD_Work_Shift.all_time        is 'Общее время смены (часов)';
comment on column GD_Work_Shift.productive_time is 'Продуктивное время смены (часов)';
comment on column GD_Work_Shift.employee_id     is 'Id работника';
comment on column GD_Work_Shift.is_open         is '1 - смена открыта';
comment on column GD_Work_Shift.count_sos       is 'Количество SOS алертов';
comment on column GD_Work_Shift.gadget_id       is 'Id гаджета';

alter table GD_Work_Shift add
  constraint Pk_Wrk_Shf
    primary key (id) using index tablespace Indexes;
alter table GD_Work_Shift add
  constraint Fk_Wrk_Shf_2_Gdt
    foreign key (gadget_id)
    references GD_Gadget (id);
alter table GD_Work_Shift add
  constraint Fk_Wrk_Shf_2_Emp
    foreign key (employee_id)
    references GD_Employee (id);
alter table GD_Work_Shift add
  constraint Fk_Wrk_Shf_2_Obj
    foreign key (object_id)
    references GD_Object (id);
